name: Metrics
on:
  schedule:
    - cron: "0 0-23/4 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        with:
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
