name: Generate Snake
on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: generate snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: snake/snake.svg
      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: master
          keep_history: true
          build_dir: snake
          commit_message: Deploying the Snake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
